version: '3'
services:
  herb-stonks:
    build: ./sample
    container_name: herb-stonks
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    volumes:
      - herb-stonks-postgres:/var/lib/postgresql/data
    networks:
      static-network:
        ipv4_address: 172.20.128.1
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - herb-stonks-grafana:/var/lib/grafana
    ports:
    - 3000:3000
    networks:
      static-network:
        ipv4_address: 172.20.128.2

volumes:
  herb-stonks-grafana:
    driver: local
  herb-stonks-postgres:
    driver: local

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
