version: '3'
services:
  herb-stonks:
    build: ./sample
    container_name: herb-stonks
    ports:
    - 8000:8000
    networks:
      static-network:
        ipv4_address: 172.20.128.1
  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
    - 9090:9090
    networks:
      static-network:
        ipv4_address: 172.20.128.2
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - 3000:3000
    networks:
      static-network:
        ipv4_address: 172.20.128.3

volumes:
  data:
    driver: local

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
