version: '3'
services:
  herb-stonks:
    build: ./sample
    container_name: herb-stonks
    ports:
    - 8000:8000
    networks:
      static-network:
        ipv4_address: 172.20.128.1
  postgres:
    build: ./postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - herb-stonks-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      static-network:
        ipv4_address: 172.20.128.2
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - herb-stonks-grafana:/var/lib/grafana
    ports:
    - 3000:3000
    networks:
      static-network:
        ipv4_address: 172.20.128.3

volumes:
  herb-stonks-grafana:
    driver: local
  herb-stonks-postgres:
    driver: local

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
